### ISSUE TITLE
Install apps through F-droid without allowing "unkown sources" 

### ISSUE THREAD

**Issue by Lobz** [Securegen/Apps#4]
We need to look into that sooner or later. I found this issue that might give us a hint https://gitlab.com/fdroid/fdroidclient/issues/131

**Comment by marciomr** [comment]
Aqui tem mais instruções sobre isso. Acho que devemos testar:

https://gitlab.com/fdroid/privileged-extension

**Comment by caiocanic** [comment]
closed by c071fcee0a5d4588e675859a57f079e5861e2ad5.
